/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as FirstLoginRouteImport } from './routes/first-login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppBranchesRouteImport } from './routes/_app.branches'
import { Route as AppChecklistsRouteImport } from './routes/_app.checklists'
import { Route as AppCompanySetupRouteImport } from './routes/_app.company-setup'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppEmergencyContactRouteImport } from './routes/_app.emergency-contact'
import { Route as AppEmployeeServicesRouteImport } from './routes/_app.employee-services'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppFaceEnrollmentRouteImport } from './routes/_app.face-enrollment'
import { Route as AppFaceSecurityRouteImport } from './routes/_app.face-security'
import { Route as AppHolidaysRouteImport } from './routes/_app.holidays'
import { Route as AppIdCardRouteImport } from './routes/_app.id-card'
import { Route as AppMyAssetsRouteImport } from './routes/_app.my-assets'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as VerifyIdEmployeeIdRouteImport } from './routes/verify-id.$employeeId'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app.attendance.index'
import { Route as AppAttendanceBranchRouteImport } from './routes/_app.attendance.branch'
import { Route as AppAttendanceCorrectionsRouteImport } from './routes/_app.attendance.corrections'
import { Route as AppAttendanceFieldRouteImport } from './routes/_app.attendance.field'
import { Route as AppAttendanceLocationsRouteImport } from './routes/_app.attendance.locations'
import { Route as AppAttendanceMineRouteImport } from './routes/_app.attendance.mine'
import { Route as AppAttendanceMissedPunchRouteImport } from './routes/_app.attendance.missed-punch'
import { Route as AppDevicesMappingRouteImport } from './routes/_app.devices.mapping'
import { Route as AppLeaveApplyRouteImport } from './routes/_app.leave.apply'
import { Route as AppLeaveApprovalsRouteImport } from './routes/_app.leave.approvals'
import { Route as AppLeaveBalanceRouteImport } from './routes/_app.leave.balance'
import { Route as AppLeaveHistoryRouteImport } from './routes/_app.leave.history'
import { Route as AppLeavePolicyRouteImport } from './routes/_app.leave.policy'
import { Route as AppLeaveReportsRouteImport } from './routes/_app.leave.reports'
import { Route as AppSettingsDevicesRouteImport } from './routes/_app.settings.devices'
import { Route as AppUsersNewRouteImport } from './routes/_app.users.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstLoginRoute = FirstLoginRouteImport.update({
  id: '/first-login',
  path: '/first-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsRoute = AppChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanySetupRoute = AppCompanySetupRouteImport.update({
  id: '/company-setup',
  path: '/company-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyContactRoute = AppEmergencyContactRouteImport.update({
  id: '/emergency-contact',
  path: '/emergency-contact',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeServicesRoute = AppEmployeeServicesRouteImport.update({
  id: '/employee-services',
  path: '/employee-services',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppFaceEnrollmentRoute = AppFaceEnrollmentRouteImport.update({
  id: '/face-enrollment',
  path: '/face-enrollment',
  getParentRoute: () => AppRoute,
} as any)
const AppFaceSecurityRoute = AppFaceSecurityRouteImport.update({
  id: '/face-security',
  path: '/face-security',
  getParentRoute: () => AppRoute,
} as any)
const AppHolidaysRoute = AppHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppIdCardRoute = AppIdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssetsRoute = AppMyAssetsRouteImport.update({
  id: '/my-assets',
  path: '/my-assets',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const VerifyIdEmployeeIdRoute = VerifyIdEmployeeIdRouteImport.update({
  id: '/verify-id/$employeeId',
  path: '/verify-id/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceBranchRoute = AppAttendanceBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceCorrectionsRoute =
  AppAttendanceCorrectionsRouteImport.update({
    id: '/corrections',
    path: '/corrections',
    getParentRoute: () => AppAttendanceRoute,
  } as any)
const AppAttendanceFieldRoute = AppAttendanceFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceLocationsRoute = AppAttendanceLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceMineRoute = AppAttendanceMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAttendanceMissedPunchRoute =
  AppAttendanceMissedPunchRouteImport.update({
    id: '/missed-punch',
    path: '/missed-punch',
    getParentRoute: () => AppAttendanceRoute,
  } as any)
const AppDevicesMappingRoute = AppDevicesMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppLeaveApplyRoute = AppLeaveApplyRouteImport.update({
  id: '/leave/apply',
  path: '/leave/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApprovalsRoute = AppLeaveApprovalsRouteImport.update({
  id: '/leave/approvals',
  path: '/leave/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveBalanceRoute = AppLeaveBalanceRouteImport.update({
  id: '/leave/balance',
  path: '/leave/balance',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveHistoryRoute = AppLeaveHistoryRouteImport.update({
  id: '/leave/history',
  path: '/leave/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLeavePolicyRoute = AppLeavePolicyRouteImport.update({
  id: '/leave/policy',
  path: '/leave/policy',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveReportsRoute = AppLeaveReportsRouteImport.update({
  id: '/leave/reports',
  path: '/leave/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDevicesRoute = AppSettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/first-login': typeof FirstLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/branches': typeof AppBranchesRoute
  '/checklists': typeof AppChecklistsRoute
  '/company-setup': typeof AppCompanySetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/devices': typeof AppDevicesRouteWithChildren
  '/emergency-contact': typeof AppEmergencyContactRoute
  '/employee-services': typeof AppEmployeeServicesRoute
  '/employees': typeof AppEmployeesRoute
  '/face-enrollment': typeof AppFaceEnrollmentRoute
  '/face-security': typeof AppFaceSecurityRoute
  '/holidays': typeof AppHolidaysRoute
  '/id-card': typeof AppIdCardRoute
  '/my-assets': typeof AppMyAssetsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/users': typeof AppUsersRouteWithChildren
  '/verify-id/$employeeId': typeof VerifyIdEmployeeIdRoute
  '/attendance/branch': typeof AppAttendanceBranchRoute
  '/attendance/corrections': typeof AppAttendanceCorrectionsRoute
  '/attendance/field': typeof AppAttendanceFieldRoute
  '/attendance/locations': typeof AppAttendanceLocationsRoute
  '/attendance/mine': typeof AppAttendanceMineRoute
  '/attendance/missed-punch': typeof AppAttendanceMissedPunchRoute
  '/devices/mapping': typeof AppDevicesMappingRoute
  '/leave/apply': typeof AppLeaveApplyRoute
  '/leave/approvals': typeof AppLeaveApprovalsRoute
  '/leave/balance': typeof AppLeaveBalanceRoute
  '/leave/history': typeof AppLeaveHistoryRoute
  '/leave/policy': typeof AppLeavePolicyRoute
  '/leave/reports': typeof AppLeaveReportsRoute
  '/settings/devices': typeof AppSettingsDevicesRoute
  '/users/new': typeof AppUsersNewRoute
  '/attendance/': typeof AppAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/first-login': typeof FirstLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assets': typeof AppAssetsRoute
  '/audit': typeof AppAuditRoute
  '/branches': typeof AppBranchesRoute
  '/checklists': typeof AppChecklistsRoute
  '/company-setup': typeof AppCompanySetupRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/devices': typeof AppDevicesRouteWithChildren
  '/emergency-contact': typeof AppEmergencyContactRoute
  '/employee-services': typeof AppEmployeeServicesRoute
  '/employees': typeof AppEmployeesRoute
  '/face-enrollment': typeof AppFaceEnrollmentRoute
  '/face-security': typeof AppFaceSecurityRoute
  '/holidays': typeof AppHolidaysRoute
  '/id-card': typeof AppIdCardRoute
  '/my-assets': typeof AppMyAssetsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/users': typeof AppUsersRouteWithChildren
  '/verify-id/$employeeId': typeof VerifyIdEmployeeIdRoute
  '/attendance/branch': typeof AppAttendanceBranchRoute
  '/attendance/corrections': typeof AppAttendanceCorrectionsRoute
  '/attendance/field': typeof AppAttendanceFieldRoute
  '/attendance/locations': typeof AppAttendanceLocationsRoute
  '/attendance/mine': typeof AppAttendanceMineRoute
  '/attendance/missed-punch': typeof AppAttendanceMissedPunchRoute
  '/devices/mapping': typeof AppDevicesMappingRoute
  '/leave/apply': typeof AppLeaveApplyRoute
  '/leave/approvals': typeof AppLeaveApprovalsRoute
  '/leave/balance': typeof AppLeaveBalanceRoute
  '/leave/history': typeof AppLeaveHistoryRoute
  '/leave/policy': typeof AppLeavePolicyRoute
  '/leave/reports': typeof AppLeaveReportsRoute
  '/settings/devices': typeof AppSettingsDevicesRoute
  '/users/new': typeof AppUsersNewRoute
  '/attendance': typeof AppAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/first-login': typeof FirstLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/attendance': typeof AppAttendanceRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/checklists': typeof AppChecklistsRoute
  '/_app/company-setup': typeof AppCompanySetupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/devices': typeof AppDevicesRouteWithChildren
  '/_app/emergency-contact': typeof AppEmergencyContactRoute
  '/_app/employee-services': typeof AppEmployeeServicesRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/face-enrollment': typeof AppFaceEnrollmentRoute
  '/_app/face-security': typeof AppFaceSecurityRoute
  '/_app/holidays': typeof AppHolidaysRoute
  '/_app/id-card': typeof AppIdCardRoute
  '/_app/my-assets': typeof AppMyAssetsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/verify-id/$employeeId': typeof VerifyIdEmployeeIdRoute
  '/_app/attendance/branch': typeof AppAttendanceBranchRoute
  '/_app/attendance/corrections': typeof AppAttendanceCorrectionsRoute
  '/_app/attendance/field': typeof AppAttendanceFieldRoute
  '/_app/attendance/locations': typeof AppAttendanceLocationsRoute
  '/_app/attendance/mine': typeof AppAttendanceMineRoute
  '/_app/attendance/missed-punch': typeof AppAttendanceMissedPunchRoute
  '/_app/devices/mapping': typeof AppDevicesMappingRoute
  '/_app/leave/apply': typeof AppLeaveApplyRoute
  '/_app/leave/approvals': typeof AppLeaveApprovalsRoute
  '/_app/leave/balance': typeof AppLeaveBalanceRoute
  '/_app/leave/history': typeof AppLeaveHistoryRoute
  '/_app/leave/policy': typeof AppLeavePolicyRoute
  '/_app/leave/reports': typeof AppLeaveReportsRoute
  '/_app/settings/devices': typeof AppSettingsDevicesRoute
  '/_app/users/new': typeof AppUsersNewRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/first-login'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/announcements'
    | '/assets'
    | '/attendance'
    | '/audit'
    | '/branches'
    | '/checklists'
    | '/company-setup'
    | '/dashboard'
    | '/departments'
    | '/devices'
    | '/emergency-contact'
    | '/employee-services'
    | '/employees'
    | '/face-enrollment'
    | '/face-security'
    | '/holidays'
    | '/id-card'
    | '/my-assets'
    | '/notifications'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/verify-id/$employeeId'
    | '/attendance/branch'
    | '/attendance/corrections'
    | '/attendance/field'
    | '/attendance/locations'
    | '/attendance/mine'
    | '/attendance/missed-punch'
    | '/devices/mapping'
    | '/leave/apply'
    | '/leave/approvals'
    | '/leave/balance'
    | '/leave/history'
    | '/leave/policy'
    | '/leave/reports'
    | '/settings/devices'
    | '/users/new'
    | '/attendance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/first-login'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/announcements'
    | '/assets'
    | '/audit'
    | '/branches'
    | '/checklists'
    | '/company-setup'
    | '/dashboard'
    | '/departments'
    | '/devices'
    | '/emergency-contact'
    | '/employee-services'
    | '/employees'
    | '/face-enrollment'
    | '/face-security'
    | '/holidays'
    | '/id-card'
    | '/my-assets'
    | '/notifications'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/verify-id/$employeeId'
    | '/attendance/branch'
    | '/attendance/corrections'
    | '/attendance/field'
    | '/attendance/locations'
    | '/attendance/mine'
    | '/attendance/missed-punch'
    | '/devices/mapping'
    | '/leave/apply'
    | '/leave/approvals'
    | '/leave/balance'
    | '/leave/history'
    | '/leave/policy'
    | '/leave/reports'
    | '/settings/devices'
    | '/users/new'
    | '/attendance'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/account-deletion'
    | '/first-login'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_app/announcements'
    | '/_app/assets'
    | '/_app/attendance'
    | '/_app/audit'
    | '/_app/branches'
    | '/_app/checklists'
    | '/_app/company-setup'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/devices'
    | '/_app/emergency-contact'
    | '/_app/employee-services'
    | '/_app/employees'
    | '/_app/face-enrollment'
    | '/_app/face-security'
    | '/_app/holidays'
    | '/_app/id-card'
    | '/_app/my-assets'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/users'
    | '/verify-id/$employeeId'
    | '/_app/attendance/branch'
    | '/_app/attendance/corrections'
    | '/_app/attendance/field'
    | '/_app/attendance/locations'
    | '/_app/attendance/mine'
    | '/_app/attendance/missed-punch'
    | '/_app/devices/mapping'
    | '/_app/leave/apply'
    | '/_app/leave/approvals'
    | '/_app/leave/balance'
    | '/_app/leave/history'
    | '/_app/leave/policy'
    | '/_app/leave/reports'
    | '/_app/settings/devices'
    | '/_app/users/new'
    | '/_app/attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountDeletionRoute: typeof AccountDeletionRoute
  FirstLoginRoute: typeof FirstLoginRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VerifyIdEmployeeIdRoute: typeof VerifyIdEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-login': {
      id: '/first-login'
      path: '/first-login'
      fullPath: '/first-login'
      preLoaderRoute: typeof FirstLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklists': {
      id: '/_app/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AppChecklistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company-setup': {
      id: '/_app/company-setup'
      path: '/company-setup'
      fullPath: '/company-setup'
      preLoaderRoute: typeof AppCompanySetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency-contact': {
      id: '/_app/emergency-contact'
      path: '/emergency-contact'
      fullPath: '/emergency-contact'
      preLoaderRoute: typeof AppEmergencyContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee-services': {
      id: '/_app/employee-services'
      path: '/employee-services'
      fullPath: '/employee-services'
      preLoaderRoute: typeof AppEmployeeServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/face-enrollment': {
      id: '/_app/face-enrollment'
      path: '/face-enrollment'
      fullPath: '/face-enrollment'
      preLoaderRoute: typeof AppFaceEnrollmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/face-security': {
      id: '/_app/face-security'
      path: '/face-security'
      fullPath: '/face-security'
      preLoaderRoute: typeof AppFaceSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holidays': {
      id: '/_app/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AppHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/id-card': {
      id: '/_app/id-card'
      path: '/id-card'
      fullPath: '/id-card'
      preLoaderRoute: typeof AppIdCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assets': {
      id: '/_app/my-assets'
      path: '/my-assets'
      fullPath: '/my-assets'
      preLoaderRoute: typeof AppMyAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify-id/$employeeId': {
      id: '/verify-id/$employeeId'
      path: '/verify-id/$employeeId'
      fullPath: '/verify-id/$employeeId'
      preLoaderRoute: typeof VerifyIdEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/branch': {
      id: '/_app/attendance/branch'
      path: '/branch'
      fullPath: '/attendance/branch'
      preLoaderRoute: typeof AppAttendanceBranchRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/corrections': {
      id: '/_app/attendance/corrections'
      path: '/corrections'
      fullPath: '/attendance/corrections'
      preLoaderRoute: typeof AppAttendanceCorrectionsRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/field': {
      id: '/_app/attendance/field'
      path: '/field'
      fullPath: '/attendance/field'
      preLoaderRoute: typeof AppAttendanceFieldRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/locations': {
      id: '/_app/attendance/locations'
      path: '/locations'
      fullPath: '/attendance/locations'
      preLoaderRoute: typeof AppAttendanceLocationsRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/mine': {
      id: '/_app/attendance/mine'
      path: '/mine'
      fullPath: '/attendance/mine'
      preLoaderRoute: typeof AppAttendanceMineRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/attendance/missed-punch': {
      id: '/_app/attendance/missed-punch'
      path: '/missed-punch'
      fullPath: '/attendance/missed-punch'
      preLoaderRoute: typeof AppAttendanceMissedPunchRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/_app/devices/mapping': {
      id: '/_app/devices/mapping'
      path: '/mapping'
      fullPath: '/devices/mapping'
      preLoaderRoute: typeof AppDevicesMappingRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/leave/apply': {
      id: '/_app/leave/apply'
      path: '/leave/apply'
      fullPath: '/leave/apply'
      preLoaderRoute: typeof AppLeaveApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/approvals': {
      id: '/_app/leave/approvals'
      path: '/leave/approvals'
      fullPath: '/leave/approvals'
      preLoaderRoute: typeof AppLeaveApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/balance': {
      id: '/_app/leave/balance'
      path: '/leave/balance'
      fullPath: '/leave/balance'
      preLoaderRoute: typeof AppLeaveBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/history': {
      id: '/_app/leave/history'
      path: '/leave/history'
      fullPath: '/leave/history'
      preLoaderRoute: typeof AppLeaveHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/policy': {
      id: '/_app/leave/policy'
      path: '/leave/policy'
      fullPath: '/leave/policy'
      preLoaderRoute: typeof AppLeavePolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave/reports': {
      id: '/_app/leave/reports'
      path: '/leave/reports'
      fullPath: '/leave/reports'
      preLoaderRoute: typeof AppLeaveReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/devices': {
      id: '/_app/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof AppSettingsDevicesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/users/new': {
      id: '/_app/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppUsersRoute
    }
  }
}

interface AppAttendanceRouteChildren {
  AppAttendanceBranchRoute: typeof AppAttendanceBranchRoute
  AppAttendanceCorrectionsRoute: typeof AppAttendanceCorrectionsRoute
  AppAttendanceFieldRoute: typeof AppAttendanceFieldRoute
  AppAttendanceLocationsRoute: typeof AppAttendanceLocationsRoute
  AppAttendanceMineRoute: typeof AppAttendanceMineRoute
  AppAttendanceMissedPunchRoute: typeof AppAttendanceMissedPunchRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
}

const AppAttendanceRouteChildren: AppAttendanceRouteChildren = {
  AppAttendanceBranchRoute: AppAttendanceBranchRoute,
  AppAttendanceCorrectionsRoute: AppAttendanceCorrectionsRoute,
  AppAttendanceFieldRoute: AppAttendanceFieldRoute,
  AppAttendanceLocationsRoute: AppAttendanceLocationsRoute,
  AppAttendanceMineRoute: AppAttendanceMineRoute,
  AppAttendanceMissedPunchRoute: AppAttendanceMissedPunchRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
}

const AppAttendanceRouteWithChildren = AppAttendanceRoute._addFileChildren(
  AppAttendanceRouteChildren,
)

interface AppDevicesRouteChildren {
  AppDevicesMappingRoute: typeof AppDevicesMappingRoute
}

const AppDevicesRouteChildren: AppDevicesRouteChildren = {
  AppDevicesMappingRoute: AppDevicesMappingRoute,
}

const AppDevicesRouteWithChildren = AppDevicesRoute._addFileChildren(
  AppDevicesRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsDevicesRoute: typeof AppSettingsDevicesRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsDevicesRoute: AppSettingsDevicesRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersNewRoute: typeof AppUsersNewRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersNewRoute: AppUsersNewRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAttendanceRoute: typeof AppAttendanceRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppChecklistsRoute: typeof AppChecklistsRoute
  AppCompanySetupRoute: typeof AppCompanySetupRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDevicesRoute: typeof AppDevicesRouteWithChildren
  AppEmergencyContactRoute: typeof AppEmergencyContactRoute
  AppEmployeeServicesRoute: typeof AppEmployeeServicesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppFaceEnrollmentRoute: typeof AppFaceEnrollmentRoute
  AppFaceSecurityRoute: typeof AppFaceSecurityRoute
  AppHolidaysRoute: typeof AppHolidaysRoute
  AppIdCardRoute: typeof AppIdCardRoute
  AppMyAssetsRoute: typeof AppMyAssetsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppLeaveApplyRoute: typeof AppLeaveApplyRoute
  AppLeaveApprovalsRoute: typeof AppLeaveApprovalsRoute
  AppLeaveBalanceRoute: typeof AppLeaveBalanceRoute
  AppLeaveHistoryRoute: typeof AppLeaveHistoryRoute
  AppLeavePolicyRoute: typeof AppLeavePolicyRoute
  AppLeaveReportsRoute: typeof AppLeaveReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAttendanceRoute: AppAttendanceRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppChecklistsRoute: AppChecklistsRoute,
  AppCompanySetupRoute: AppCompanySetupRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDevicesRoute: AppDevicesRouteWithChildren,
  AppEmergencyContactRoute: AppEmergencyContactRoute,
  AppEmployeeServicesRoute: AppEmployeeServicesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppFaceEnrollmentRoute: AppFaceEnrollmentRoute,
  AppFaceSecurityRoute: AppFaceSecurityRoute,
  AppHolidaysRoute: AppHolidaysRoute,
  AppIdCardRoute: AppIdCardRoute,
  AppMyAssetsRoute: AppMyAssetsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppLeaveApplyRoute: AppLeaveApplyRoute,
  AppLeaveApprovalsRoute: AppLeaveApprovalsRoute,
  AppLeaveBalanceRoute: AppLeaveBalanceRoute,
  AppLeaveHistoryRoute: AppLeaveHistoryRoute,
  AppLeavePolicyRoute: AppLeavePolicyRoute,
  AppLeaveReportsRoute: AppLeaveReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountDeletionRoute: AccountDeletionRoute,
  FirstLoginRoute: FirstLoginRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VerifyIdEmployeeIdRoute: VerifyIdEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
